### ISSUE TITLE
Don`t works with a local *.html files

### ISSUE THREAD

**Issue by kramola-RU** [eight04/select-text-inside-a-link-like-opera#11]
Hello!
(and **many many thanks** for fix issue #9)

I use the [**SingleFile**](https://chrome.google.com/webstore/detail/singlefile/mpiodijhokgodhhofbcjdecpffjipkle) to saves pages on disk.

But the script don`t works with a local ***.html** files.

Could you add the ability to work with a local files ?

**Comment by eight04** [comment]
Which script manager do you use? I think you have to grant the file-access permission for the extension.

**Comment by kramola-RU** [comment]
I don`t use any scriptmanager.
I just install the script like extension. And in the "details" no option to
grant the file-access permission (see attached screenshot).

But you are right -- with the Violentmonkey I can grant the permissions and
fix the problem.

*THANKS A LOT (again) !!!!!!!!!*

By the way, with the "Tampermonkey"+"Select text inside a link like Opera"
I got empty pages at the https://lenta.ru/ and https://www.gazeta.ru/

With the Violentmonkey -- no problems

чт, 6 июн. 2019 г. в 18:19, eight <notifications@github.com>:

**Comment by eight04** [comment]
https://github.com/Tampermonkey/tampermonkey/issues/722

**Comment by kramola-RU** [comment]
the advice from my friends to fix the problem:  https://prnt.sc/nyqarh

**Comment by eight04** [comment]
I'm closing this issue since the problem described in the title is resolved. Please subscribe to the issue in Tampermonkey repo.
