### ISSUE TITLE
The script disrupts some sites

### ISSUE THREAD

**Issue by Almashina** [eight04/select-text-inside-a-link-like-opera#12]
Script disrupts some sites, such as https://lenta.ru/ and https://www.rambler.ru/ .
When script is activated only a gray/white blank screen is visible.
mozilla 56.0.2 + tampermonkey 4.9.5941 + select-text-inside-a-link-like-opera 5.0.3

**Comment by eight04** [comment]
See https://github.com/Tampermonkey/tampermonkey/issues/722
