### ISSUE TITLE
Poor performance on data-heavy websites

### ISSUE THREAD

**Issue by tomasz1986** [eight04/select-text-inside-a-link-like-opera#15]
I have found out that https://data.syncthing.net loads almost twice slower with the user script enabled compared to when it is turned off.

In short,

1. Chromium 89 x64 / Windows 10 / Core 2 Duo T7700

   script on - 37s
   script off - 20s

2. Chromium 89 x64 / Windows 10 / Ryzen 4350G

   script on - 12s
   script off - 7s

For reference and specific data, please see https://github.com/syncthing/syncthing/issues/7662.

**Comment by eight04** [comment]
This script runs on mouse events so it shouldn't affect page load.

1. Which script manager do you use?
2. Did you test with only this script enabled? If yes then the 17s difference might come from the extension bootstrap. In this case, any `document-start` script requires the extension to bootstrap early. Try changing `// @run-at document-start` to `// @run-at document-idle`.

On my machine (Chrome 90 / Windows 10 / Core i5-4200U), it always takes ~5s to get the first paint and ~10s to load the graph with or without turning on the script.
