### ISSUE TITLE
Support Tampermonkey on Firefox

### ISSUE THREAD

**Issue by Keith94** [eight04/select-text-inside-a-link-like-opera#3]
In Firefox 54 with [Tampermonkey](https://addons.mozilla.org/firefox/addon/tampermonkey/) installed, the script doesn't seem to work.

**Comment by eight04** [comment]
I can't reproduce it.

Firefox 54.0a1
Tampermonkey 4.3.5384
Select text inside a link like opera 4.0.12

**Comment by Keith94** [comment]
Hmm, it doesn't work on domains github.com and addons.mozilla.org. Can you check those?

**Comment by eight04** [comment]
I think it doesn't relate to the script, but Tampermonkey just doesn't work under these domains.

**Comment by eight04** [comment]
See https://github.com/Tampermonkey/tampermonkey/issues/361.

**Comment by Keith94** [comment]
@eight04 Thanks for filing. :)
