### ISSUE TITLE
Don`t works on some websites

### ISSUE THREAD

**Issue by kramola-RU** [eight04/select-text-inside-a-link-like-opera#9]
For example, at https://3dnews.ru/news  I can`t select the big headlines.

See the screenshot:

![3dnews ru](https://user-images.githubusercontent.com/51376332/58895353-5e17a800-86fc-11e9-9f7e-e208c0e1c3ab.png)

Could you fix this behavior?

**Comment by eight04** [comment]
For some reason, the `dragstart` handler is not called when dragging the title.

A minimal test case:
https://codepen.io/eight04/pen/BeEaYN

**Comment by kramola-RU** [comment]
I tried the:  https://greasyfork.org/ru/scripts/6911-select-like-opera  --- it works.But I don`t like the "Select like opera" because of  another bug.04.06.2019, 19:52, "eight" <notifications@github.com>:For some reason, the dragstart handler is not called when dragging the title.
A minimal test case:
https://codepen.io/eight04/pen/BeEaYN

**Comment by kramola-RU** [comment]
WOW!!! Its works! Thanks a lot!

THANK YOU !
THANK YOU !
THANK YOU !

I tried all available solutions for selecting like Opera, but no one works
exactly like the Opera :(
Only yours NOW !!!

чт, 6 июн. 2019 г. в 07:33, eight <notifications@github.com>:
